packages/climbingapp/ios/climbingApp/.gitattributes
- xcode의 최상위 프로젝트 관리 패키지인 .pbxproj 파일은 ide 등 로컬 환경에 의해 변경되어 conflict가 발생할 수 있으나 gitignore에는 넣을 수 없는 이슈.
- gitattributes 파일을 만들어 병합되지 않고 비교 되지 않게 하는 방법으로 우회
- 아래 옵션 부여
- crlf : crlf <=> cr 변환을 사용하지 않. 
- diff : 파일을 diff하지 않음.
- merge : 파일을 병합하지 않음.
=> chore: add .gitattributes for ios pbxproj file

packages/climbingapp/App.tsx, packages/climbingapp/src/hooks/useAuth.ts, packages/climbingapp/src/store/index.ts, packages/climbingapp/src/store/slices/auth.ts, packages/climbingapp/src/store/slices/index.ts
- \#37
- RN redux store, slice 생성
- demo 코드로 auth slice 구현 => 추후 UserInfo에 필요한 속성 추가
- useAuth 훅 구현 => 추후 변경할 수 있음
- store 생성 및 app.tsx 파일에 적용 
- Provider가 있는 파일에서 직접적으로 data read, write 불가, 하위 컴포넌트에서 redux 사용 
- auth slice에서 reducer 함수를 정의하고 rootReducer에 등록
- useAuth를 통해 hook 형식으로 state, function 제공
=> chore: redux store and slices setting

packages/climbingapp/App.tsx, packages/climbingapp/babel.config.js, packages/climbingapp/index.js, packages/climbingapp/ios/Podfile.lock, packages/climbingapp/package.json, packages/climbingapp/src/component/bottomSheet/BottomSheet.tsx, packages/climbingapp/src/component/dropdown/DropDown.stories.tsx, packages/climbingapp/src/component/dropdown/DropDown.tsx, packages/climbingapp/src/navigation/screens/main/BoardScreen.tsx, packages/climbingapp/src/store/slices/index.ts, yarn.lock
- \#22
- 드롭다운 컴포넌트 구현 (드롭다운 + 바텀시트)
- 드롭다운
-  드롭다운 아이콘 클릭 시 바텀시트 노출
- 바텀 시트의 ref를 컨트롤하는 함수 사용  (onPress 함수에 전달)
- 바텀시트
- 바텀 탭보다 아래에서 출력될 수 있는 바텀시트 모달 사용
- 내부 컨텐츠는 flatList로 제공   
- react-native-animated, react-native-gesture-handler,  @gohrom/bottom-sheet 라이브러리 추가
-  react-native-animated, react-native-gesture-handler : 바텀시트의 움직임이나 시각 효과에 필요
- @gohrom/bottom-sheet:  바텀시트를 제공하는 라이브러리 
- AreaDropDown 컴포넌트 : 회원가입에 필요한 정보 제공 컴포넌트, 바텀시트의 ref를 통해 호출
- MyBottomSheet 컴포넌트 : React.forwardRef 를 통해 자식의 ref를 부모가 사용할 수 있도록 함
- App.tsx 파일  BottomSheetModalProvider로 감쌈: 앱 전체에서 사용할 수 있음
=> Dropdown and bottom sheet

packages/climbingapp/android/app/build.gradle, packages/climbingapp/ios/climbingApp.xcodeproj/project.pbxproj, packages/climbingapp/ios/climbingApp.xcodeproj/xcshareddata/xcschemes/climbingApp.xcscheme
Fixes #67 
- android runtime 때 Config 파일을 가지고 오지 못하는 이슈 해결
- build.gradle (app) 의 defaultConfig 의 패키지네임 입력 오류 해결 
- ios의 build pre-action 파일 경로 변경 (모노레포 이슈)
- xcode => 상단 product => scheme => edit scheme => build => pre-actions =>. path를 모노레포에 맞게 (../..) 2 개 더 전으로 이동
- defaultConfig의 resValue로 등록한 속성 => 패키지 이름 필요 => com.climbingapp 으로 제대로 입력 후 정상 동작
=> fix: fix android configuration for .env

packages/climbingweb/src/components/common/DropDown/index.stories.tsx, packages/climbingweb/src/components/common/DropDown/index.tsx, packages/climbingweb/src/components/common/Input/StringCount.tsx, packages/climbingweb/src/components/common/Input/index.stories.tsx, packages/climbingweb/src/components/common/Input/index.tsx
Fixes #92 
Fixes #93 
- Input 컴포넌트 뷰 구현  
- drop down 컴포넌트  뷰 구현
-  input 컴포넌트
- props (rightnode)   =>  컴포넌트 ui 내부에 노드 추가 가능
- dropdown
- 현재 뷰만 존재,  bottomsheet와 연동해 사용
=> feat: implement input and dropdown component for web

packages/climbingweb/pages/_app.tsx, packages/climbingweb/pages/center/[cid].tsx, packages/climbingweb/pages/center/request/index.tsx, packages/climbingweb/pages/index.tsx, packages/climbingweb/pages/report/index.tsx, packages/climbingweb/pages/search/index.tsx, packages/climbingweb/pages/setting/index.tsx, packages/climbingweb/src/components/HomeFeed/FeedHeader/FeedHeader.tsx, packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx, packages/climbingweb/src/components/SettingInfo/EditMyInfo.tsx, packages/climbingweb/src/components/common/BottomSheetContents/FeedEditSheet.tsx, packages/climbingweb/src/components/common/BottomSheetContents/LeaveSheet.tsx, packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/ListSheet.tsx, packages/climbingweb/src/components/common/BottomSheetContents/type.d.ts, packages/climbingweb/src/components/common/DropDown/index.tsx, packages/climbingweb/src/components/common/IconButton.tsx, packages/climbingweb/src/components/common/bottomNav/NavBar.tsx, packages/climbingweb/src/components/common/button/Button.tsx, packages/climbingweb/src/hooks/useBtSheet.tsx, packages/climbingweb/src/store/index.ts, packages/climbingweb/src/store/slices/index.ts, packages/climbingweb/src/store/slices/uiSlice.ts, packages/climbingweb/tailwind.config.js
Fixes #116 
- 각 페이지마다 사용되는 바텀시트, 상황 별 시트 구현 및 적용
- 바텀시트 사용 페이지
-  홈,  암장 (리뷰, 수정), 게시글 신고, 개인정보 수정, 설정 
- 시트 종류
-  ListSheet :  헤더와 컨텐츠 리스트를 나열하는 시트
-  LeaveSheet : 타이틀, 취소, 확인 버튼의 시트
=> feat: 페이지 별 바텀시트 적용

packages/climbingweb/pages/report/index.tsx, packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/ListSheet.tsx, packages/climbingweb/src/components/common/BottomSheetContents/type.d.ts, packages/climbingweb/src/components/common/DropDown/index.tsx, packages/climbingweb/src/hooks/queries/useCreateReport.ts, packages/climbingweb/src/interface/ReportData.ts
- feat: 신고하기 백엔드 로직 추가
- 먼저 올린 풀 리퀘스트 먼저 머지 부탁 드립니다.
- report 페이지 리팩터링
const REPORT_LIST 따로 뺌, api 호출을 위한 커스텀 훅 사용
- listSheet 컴포넌트 기능 변경 
바텀시트 list 선택시 선택한 값을 핸들링 할 수 있도록 선택한 값을 props로 받은 함수에 넣음
- ListSheetProps 인터페이스 변경
onSelect props 를 필수로 받도록 변경
- DropDown 컴포넌트 변경
애로우 버튼 터치 시에만 바텀 시트가 생기는 것이 아닌, 전체 컴포넌트 터치 시 바텀 시트가 나타나도록 변경, value 값을 props로 받을 수 있도록 변경하여, 상위 컴포넌트의 value 값을 보여주기만 하도록 변경
- `/posts/${reportData.postId}/report` api hooks 추가
- `/posts/${reportData.postId}/report` api 관련 data 인터페이스 ReportData 추가
=> feat: 신고하기 백엔드 로직 추가

packages/climbingweb/pages/center/index.tsx, packages/climbingweb/src/components/common/CenterResult/CenterResultList.tsx, packages/climbingweb/src/hooks/queries/center-controller/useGetCenterList.ts
feat: 암장 메인 화면 백엔드 로직 추가
- 암장 메인 화면 백엔드 로직 추가
- CenterResultList 컴포넌트 앞선 PR 에 맞게 props 변경
- GET /centers api 의 useQuery hooks 추가
=> feat: 암장 메인 화면 백엔드 로직 추가

packages/climbingweb/pages/center/[cid].tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterCharge.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterDetailInfo.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterFacilities.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterHoldList.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterOperatingTime.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterPost.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterReview.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterSectorList.tsx, packages/climbingweb/src/components/CenterInfo/CenterInfoContent.tsx, packages/climbingweb/src/components/CenterInfo/CenterInfoHead.tsx, packages/climbingweb/src/components/Comments/ReviewComment.tsx, packages/climbingweb/src/components/common/TabBar/index.tsx, packages/climbingweb/src/hooks/queries/center-controller/useFindCenter.ts, packages/climbingweb/src/hooks/queries/center-controller/useFindReviewByCenter.ts, packages/climbingweb/src/hooks/queries/center-controller/useGetCenterPosts.ts
feat: 암장 상세 정보 전체 백엔드 로직 추가
🥇 TODO
1. CenterInfoHead 컴포넌트 Icon 클릭 핸들러 로직 추가 : 기획 필요
2. 이미지로 보기 클릭 핸들러 로직 추가 : 기획 필요
- CenterDetailPage (암장 상세 전체 페이지 컴포넌트) 리팩터링
1. url 에서 cid 받아와 백엔드 api call 하도록 변경
- 암장 상세정보 탭 관련 컴포넌트 추가
1. CenterCharge : 요금 정보 출력 컴포넌트 (이미지로 보기 포함)
2. CenterFacilities : 이용시설 출력 컴포넌트
3. CenterHoldList : 홀드 정보 출력 컴포넌트
4.  CenterOperatingTime : 이용 시간 출력 컴포넌트 (이미지로 보기 포함)
5. CenterSectorList : 섹터 정보 출력 컴포넌트
- CenterPost (암장 게시글 컴포넌트) 리팩터링
1. 섬네일 클릭 시 라우팅 해주는 로직 추가
- CenterReview (암장 리뷰 컴포넌트) 리팩터링
1. 백엔드 로직 추가
- CenterInfoContent (암장 상세 페이지 탭 컴포넌트) 리팩터링
1. 데이터 전체를 받아와 하위 컴포넌트에 데이터를 나누어 props 로 전달 하도록 변경
- CenterInfoHead (암장 상세 페이지 헤더 컴포넌트) 리팩터링
1. 클릭 핸들러 추가
- ReviewComment (암장 리뷰 개별 컴포넌트) 리팩터링
1. props 이름 백엔드에 맞게 변경
2. 삭제된 게시글 입니다. 가 백엔드에 반영되어 있지 않아, 프론트에서 해당 로직 변경
- TabBar (탭 …
=> feat: 암장 상세 정보 전체 백엔드 로직 추가

packages/climbingweb/src/components/common/Alert/Alert.tsx, packages/climbingweb/src/components/common/EmptyContent/EmptyContent.tsx, packages/climbingweb/src/components/common/Error/ErrorContent.tsx, packages/climbingweb/src/components/common/Loading/Loading.tsx, packages/climbingweb/types/common/index.d.ts
feat: 공통 요소 일부 추가
- Alert 컴포넌트 추가 (하단에 메시지를 2초간 보여줌)
사용 예시
const [openAlert, setOpenAlert] = useState<boolean>(false);
const handleAlert = () => {
setOpenAlert(true);
};
return (
<button onClick={handleAlert}>alert</button>
{openAlert ? (
<Alert message="알림" setAlertOpenState={setOpenAlert} />
) : null}
)
- Loading 컴포넌트 추가
- ErrorContent 컴포넌트 추가
클라온 서버 error response 에 맞게 사용 가능하도록 추후 디자인 나오면 변경
현재는 error response 에 맞춰 메시지만 보여주는 div 인 임시 컴포넌트
- ServerError response type 추가
- EmptyContent 컴포넌트 추가
서버의 데이터가 없을 경우 사용할 공통 Empty 컴포넌트, 추후 디자인 변경 할 수 있음
넓은 빈 공간에 메시지만 중간에 보여주는 div 인 임시 컴포넌트
=> feat: 공통 요소 일부 추가

packages/climbingweb/pages/_app.tsx, packages/climbingweb/pages/center/request/index.tsx, packages/climbingweb/pages/center/review/index.tsx, packages/climbingweb/pages/index.tsx, packages/climbingweb/pages/report/index.tsx, packages/climbingweb/src/components/SettingInfo/EditMyInfo.tsx
react-spring-bottom-sheet css 를 글로벌하게 import 하여 BottomSheet 컴포넌트를 사용하는 파일마다 일일이 css 따로 import 하지 않아도 되게 변경
- 
-
=> fix: react-spring-bottom-sheet css 글로벌 import

packages/climbingapp/src/component/webview/CustomWebView.tsx, packages/climbingweb/pages/_app.tsx, packages/climbingweb/src/hooks/useRNMessage.ts, packages/climbingweb/src/store/slices/auth.ts, packages/climbingweb/src/utils/reactNativeMessage.ts
- RN -> web 으로 토큰 전달 시  api 먼저 호출되어 발생하던 에러 해결
- 토큰 전달 완료 전까지 Loading 창 return
- 앱 메시지   type 이름  messageFromApp 으로 사용한 걸 token 으로 이름 변경
- _app.tsx:  
-  useLayoutEffect를 사용해 렌더링 전에 effect 작업 수행
-  로딩 화면 추가
-  useRNMessage:
-  RN 메시지 주고 받는 로직 훅으로 구현, 사용
-  reactNativeMessage.ts : 
- 기존 사용하던 통신 로직,   토큰 관련 내용 제거
- 추후에 사용안하면 제거
=> fix: 앱에서 로그인 시 토큰 받아오는 타이밍 fix

packages/climbingweb/pages/center/[cid].tsx, packages/climbingweb/pages/center/index.tsx, packages/climbingweb/pages/feed/[fid].tsx, packages/climbingweb/pages/index.tsx, packages/climbingweb/pages/search/index.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterPost.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterReview.tsx, packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx, packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx, packages/climbingweb/src/components/SearchResult/UserResult/UserResult.tsx, packages/climbingweb/types/response/center/index.d.ts
refactor: 공통 컴포넌트 추가 적용 및 자잘한 오류 수정
- 공통 컴포넌트 `Loading` `ErrorContent` `EmptyContent` 필요한 부분 적용
1. /center/[cid]
2. /center
3. /feed/[fid]
4. / (home)
5. /search
- router.query 의 type 이 string | string[] | undefined 라서 string 으로 거르는 로직의 코드 변경
1. /center/[cid]
2. /feed/[fid]
- next.js 싱글톤 Router 사용하던 것 useRouter 로 변경
1. / (home)
2. <HomeFeed />
- react-query hooks 를 통해 가져온 data 의 변수명을 일관성 있게 수정
1. /search
2. <HoldListModal />
- CenterPreviewReponse 인터페이스 key 값 잘못 사용 되었던 것 수정
=> refactor: 공통 컴포넌트 추가 적용 및 자잘한 오류 수정

packages/climbingweb/src/components/User/UserHead.tsx
fix: UserHead 컴포넌트 apeIndex 표기 오류 수정
- UserHead 컴포넌트에 apeIndex 가 - 값 일 경우 + 가 같이 보이던 현상 수정
=> fix: UserHead 컴포넌트 apeIndex 표기 오류 수정

packages/climbingweb/src/components/HomeFeed/FeedHeader/FeedHeader.tsx, packages/climbingweb/src/components/User/UserFeed.tsx, packages/climbingweb/src/components/User/UserFeedList.tsx, packages/climbingweb/src/components/common/profileImage/ProfileImage.tsx, packages/climbingweb/src/hooks/queries/center/queryKey.ts, packages/climbingweb/types/response/center/index.d.ts, packages/climbingweb/types/response/user/index.d.ts
개인 페이지 라우팅 추가
- 피드 헤더 클릭 시 라우팅 되도록 함수 추가
- 관련 컴포넌트 : FeedHeader
- 개인 페이지 게시물 피드 클릭 시 라우팅 되도록 함수 추가
- 관련 컴포넌트 : UserFeed, UserFeedList
- 개인 프로필 이미지 크기 wireframe 에 맞게 수정
- center 관련 QueryKey 코드 일관성 있게 변경
- UserCenterPreviewResponse 인터페이스 누락 된 것 추가 및  연관 인터페이스 수정 (CenterClimbingHistoryResponse)
=> fix: 개인페이지 라우팅 변경

packages/climbingweb/pages/_app.tsx, packages/climbingweb/pages/setting/index.tsx, packages/climbingweb/src/components/common/Toast/Toast.tsx, packages/climbingweb/src/components/common/Toast/ToastClient.tsx, packages/climbingweb/src/components/dev/Login.tsx, packages/climbingweb/src/hooks/useToken.ts
localStorage 를 이용한 임시 로그인 기능 추가
- localStorage 를 이용한 로그인 로그아웃 기능 추가
web api localStorage 이용 했기 때문에, 로그아웃 하기 전엔 토큰 계속 유지 될 것입니다.
=> feat: 임시 로그인 기능 추가

packages/climbingweb/pages/feed/create/index.tsx, packages/climbingweb/src/components/CreateFeed/UploadImageList/UploadImage.tsx, packages/climbingweb/src/components/CreateFeed/UploadImageList/UploadImageButton.tsx, packages/climbingweb/src/components/CreateFeed/UploadImageList/index.tsx, packages/climbingweb/src/hooks/queries/post/queries.ts, packages/climbingweb/src/hooks/queries/post/queryKey.ts, packages/climbingweb/src/hooks/useCreatePostForm.ts, packages/climbingweb/src/store/slices/createFeed.ts, packages/climbingweb/src/store/slices/index.ts
Fixes #issue number
##Image
- post 관련 데이터들 리덕스로 옮김
- 이미지 s3에 업로드 구현
- 포스트 생성 적용
- post 관련 데이터 => 리덕스
- 데이터 관리를  redux store의 createSlice 에서 주관하기 위해
- 이미지 s3 업로드 로직 구현
-  getContentsList(),  useGetContentsList()  사용
-  설정한 이미지만큼 한번에 여러 요청
-  onSuccess 일 때: 이미지 저장 성공 시 포스트 생성 동기적으로 요청 
- onError일 때:  에러 alert
- 포스트 생성 적용
- useGetContnetsList() 수행 후 성공 시 동기적 수행
- onsuccess : 포스트 생성 성공 alert 후 home 화면 이동
- onError :  alert 후 **페이지 refresh**
=> feat: 포스트 이미지 업로드 구현 

packages/climbingweb/pages/feed/[fid].tsx, packages/climbingweb/pages/feed/create/index.tsx, packages/climbingweb/src/components/CreateFeed/CenterSearchInput.tsx, packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx, packages/climbingweb/src/components/HomeFeed/FeedSectorInfo/FeedSectorInfo.tsx, packages/climbingweb/src/components/ImageSlider/ImageSlider.tsx, packages/climbingweb/src/components/User/MiniHold.tsx, packages/climbingweb/src/components/User/UserFeed.tsx, packages/climbingweb/src/components/User/UserHead.tsx, packages/climbingweb/src/components/User/UserRecord.tsx, packages/climbingweb/src/components/User/UserRecordList.tsx, packages/climbingweb/src/components/common/PageSubTitle/PageSubTitle.tsx, packages/climbingweb/src/components/common/profileImage/ProfileImage.tsx, packages/climbingweb/src/hooks/queries/center/queryKey.ts, packages/climbingweb/src/interface/CenterName.ts
Please include a summary of the change and which issue is fixed.
- 피드 관련 마크업 수정
1. AppBar 클라온 로고에서 뒤로가기로 수정
2. UserHead 인스타 프로필 아이콘  클릭 핸들러 추가 (작동은 나중에)
3. ProfileImage size 지정 가능하도록 변경 및 기본 사이즈 지정(40px)
나머지 css 수정
1. HomeFeed 홀드 정보 잘 뜨게 수정
2. MiniHold 컴포넌트 css 수정
3. UserFeed css 수정
4. UserRecord css 수정 및 마크업 수정
- hold 갯수가 0 개인 경우 필터링 하는 로직 추가
post 생성 시 hold 개수가 0 개 인 경우는 아예 해당 hold 를 추가하지 않아야 하는데, 0개로 추가하는 현상이 있었음 이를 해결
- post create 페이지 암장 검색 후 hold modal 뜨는 것 자잘한 오류 수정 및 로직 정리
1. 페이지 암장 검색 input 컴포넌트 css 동작이 이상한 것 수정( 검색 결과가 없는데, 아래 border 가 round css 미적용 되어 부자연 스러워 보였음)
2. CenterSearchInput 컴포넌트 및 Modal 컴포넌트 server state 를 page 로 옮김
이전엔 해당 컴포넌트 들이 server state 를 가지고 있어서 일관성이 없었으나, page 로 옮기고 해당 컴포넌트들은 view 만 보여주도록 변경
3. findHoldInfoByCenter 관련 쿼리 return 값 후처리를 modal 컴포넌트에서 하도록 변경
4. …
=> fix: 1차 자체 QA

packages/climbingweb/pages/index.tsx, packages/climbingweb/src/components/HomeFeed/FeedContent/FeedContent.tsx, packages/climbingweb/src/components/SearchResult/UserResult/UserResult.tsx, packages/climbingweb/src/components/common/AppBar/index.tsx
resolves #171 
resolves #170 
resolves #169 
#171 검색버그
#170 피드 댓글 이슈
#169 헤더 GNB 이슈
- 헤더 GNB 이슈
css position : sticky 는 상위 요소가 overflow 속성을 가지고 있으면 적용이 되지 않아서 fixed 로 적용
- 피드 댓글 이슈
상의 후 댓글이 0개인 경우 댓글 달기 문자열이 보이도록 추가
- 검색 버그
next/Image 컴포넌트는 src 의 default 값의 문제가 있어 ProfileImage 컴포넌트에 관련 문제를 해결해 둔 적이 있었음
해당 버그도 Image 컴포넌트 src 의 default 값 문제라서 ProfileImage 로 문제 해결
=> fix: #169, #170, #171 해결

packages/climbingweb/pages/index.tsx, packages/climbingweb/src/components/ImageSlider/ImageSlider.tsx, packages/climbingweb/src/components/User/UserFeed.tsx, packages/climbingweb/src/components/User/UserRecord.tsx, packages/climbingweb/src/components/common/LaonList/LaonItem.tsx
resolves #179
resolves #180
resolves #181
#179 추천게시글 요소 위 아래 회색 줄 삭제
#180 이미지가 이미지 컴포넌트 크기에 따라 찌그러지는 현상
#181 내 라온 페이지 이미지 깨지는 현상
- #179   
기존 추천 게시글엔 회색 줄이 존재 했었음..
- #180 
이미지 컴포넌트 크기에 맞춰 찌그러지는 현상 수정 (objectFi='contain' option 이용)
- #181 
ProfileImage 를 사용하면 되는 것을 일반 Image 사용하여 생기던 현상 수정
=> [WEB] #179, #180, #181 해결

packages/climbingapp/android/app/build.gradle, packages/climbingapp/android/app/src/main/AndroidManifest.xml, packages/climbingapp/android/build.gradle, packages/climbingapp/android/gradle.properties
안드로이드 릴리즈 번들 빌드를 위한 버전 및 설정 변경
- 안드로이드 릴리즈를 위한 타겟 SDK 버전 30 => 31
- 코틀린 1.4.0 => 1.7.0
- gradle 버전 4.2.2 => 7.1.3
- 배포 버전코드 업
- 배포 버전 1.0.1
=> chore: 안드로이드 release 파일 빌드를 위한 빌드 관련 코드 변경

packages/climbingapp/src/component/webview/CustomWebView.tsx, packages/climbingapp/src/hooks/useAuth.ts, packages/climbingapp/src/navigation/LoginNavigator.tsx, packages/climbingapp/src/store/slices/auth.ts, packages/climbingapp/src/utils/storage.ts
Fixes #188 
- 앱 내 토큰 저장 및 재실행 시 auto login 적용
- authorize, logout 함수 미동작 버그 fix
- 토큰 저장
-  로그인 시  sign-in api  response 를 async storage 에 저장
- 앱 실행 시 토큰 확인
-  앱 실행 시  navigator에서  useLayoutEffect 사용 (화면 렌더링 전에 토큰 값 확인 후 각각 다른 화면으로 이동)
-  홈 화면 이동 ( 토큰 존재 & isCompletedSignUp = true)
- 로그인 화면 이동 (토큰 미존재,  토큰 존재 &   isCompletedSignUp = false)
=> fix: 앱 재실행 시 토큰 저장 확인 후 자동 로그인 적용, 로그아웃 시 토큰만료 후 로그인 화면 이동하도록 로직 수정

packages/climbingapp/src/hooks/useAuth.ts, packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx, packages/climbingapp/src/types/type.d.ts
Fixes #189
로그인을 하지 않았을 때 회원가입으로 넘어가는 이슈 fix
- 소셜 로그인 진행  중 취소 에러 대응 x =>  로그인 화면으로 돌아옴
- 서버 에러 발생 시 alert 노출
-  에러 번호
-  에러 메시지 노출
- 네트워크 에러 따로 처리   ( 제목 : 에러,  문구: 서버에 문제가 있습니다. 잠시 후 다시 시도해주세요.)
-  sign-in api 정상 수신 시  로그인 / 회원가입 분기 처리
=> fix: oauth 로그인 실패 시 회원가입 화면으로 바로 넘어가는 로직 수정

packages/climbingapp/src/component/profile-image/ProfileImage.tsx, packages/climbingapp/src/hooks/queries/sign/queries.ts, packages/climbingapp/src/hooks/useAuth.ts, packages/climbingapp/src/navigation/screens/auth/ConnectWithInstagramScreen.tsx, packages/climbingapp/src/navigation/screens/auth/SignUpStepOneScreen.tsx, packages/climbingapp/src/store/slices/auth.ts, packages/climbingapp/src/store/slices/index.ts, packages/climbingapp/src/store/slices/s3util.ts, packages/climbingapp/src/utils/constants.ts, packages/climbingapp/src/utils/errorMessage.ts
Fixes #191 #190 
- 닉네임 체크 로직 수정
- 프로필 사진 업로드 기능 추가
-  프로필 사진 S3 업로드 api 추가 
- 닉네임 중복 체크 로직은 요구사항과 다르게 api가 인풋의 입력에 따라 바로 호출되도록 함,  
-  버튼이 닉네임 미입력 시 disabled 되어야 하는데 버튼을 누를 때 닉네임 중복을 체크한다는 것은 어색함
- 프로필 업로드 기능 추가
-  프로필 이미지 파일 path S3utils. 슬라이스에 저장 
- sign-up api 호출 전 이미지 업로드 api 먼저 수행 후 성공 시 진행하도록 로직 적용
- 로그인 인증 시 axios header에 토큰 저장
- 
- 닉네임 체크 로직 동작 화면
=> [WIP] fix: #191, #190 버그 수정  ( 닉네임 체크, 프로필 사진 S3 업로드)

packages/climbingapp/android/app/src/main/AndroidManifest.xml, packages/climbingapp/src/component/webview/CustomWebView.tsx, packages/climbingapp/src/utils/constants.ts
Fixes #77 
- 앱 내  웹뷰 환경의 자연스러움을 위한 스타일 적용
- 앱 코드 내에서 적용
- 참고 자료
-  https://shylog.com/settings-for-a-more-complete-webview/
- 
- android 가로모드 고정
- webview component 속성 적용
-  유저가 pinch zoom in, out 을 하지 못하게 설정
- javascript 삽입
-  user-select 속성 none 적용  (텍스트 드래그 불가)
=> fix: android 가로모드 고정, pinch zoom 막기, user-select (텍스트 복사 등) 막기 적용

packages/climbingapp/src/hooks/useGetTokenFromStorage.ts, packages/climbingapp/src/navigation/LoginNavigator.tsx, packages/climbingapp/src/store/slices/auth.ts
- auto login 기능 화면 플로우 버그 수정
-  useLayoutEffect 제거 (  디바이스에서 토큰을 가져오기 전에 화면 분기 처리 로직이 진행되어서 버그 발생)
-  redux-thunk 사용
- 디바이스에 저장된 토큰을 가져올 때 비동기로 불러옴, 이를 판단할 수 있는 loading 상태가 필요
- useGetTokenFromStorage 훅을 작성해 해당 로직을 관리
=> fix: redux 비동기 상태 체크 적용 => auto 로그인 분기처리 로직수정

packages/climbingweb/pages/feed/create/index.tsx, packages/climbingweb/pages/report/[fid].tsx, packages/climbingweb/pages/users/name/[uname]/index.tsx, packages/climbingweb/src/components/SearchResult/UserResult/UserResult.tsx, packages/climbingweb/src/hooks/queries/center/queryKey.ts, packages/climbingweb/src/hooks/queries/laon/queryKey.ts, packages/climbingweb/src/hooks/queries/post/queryKey.ts, packages/climbingweb/src/hooks/queries/user/queryKey.ts
#212 #214 
refac&fix: #212, #214 버그 fix 와 useMutation custom hooks 기본 options 사용 가능하도록 리팩터링
버그를 해결하기 위해 기본 options 사용 가능하도록 지원이 필요해서 리팩터링을 같이 진행함
- #212 라온 신청
1. 라온 신청 시, 버튼 disabled 변경 처리가 되지 않은 점 수정
2. 라온 신청 성공 시, 신청 완료 toast 추가
3. 라온 신청 실패 시, 신청 실패 toast 추가
- #214 게시글 신고 버스
1. 버그 게시글 작성 성공 시, 신청 완료 toast 추가
2. 버그 게시글 작성 실패 시, 신청 실패 toast 추가
- useMutation custom hooks 리팩터링
1. hooks/queries/center/queryKey.ts 변경사항
useMutation 을 사용하는 custom hooks 가 tanstack query 의 기본 useMutation options 를 사용 할 수 있도록 변경
2. hooks/queries/laon/queryKey.ts 변경사항
useMutation 을 사용하는 custom hooks 가 tanstack query 의 기본 useMutation options 를 사용 할 수 있도록 변경
3. hooks/queries/post/queryKey.ts 변경사항
useMutation 을 사용하는 custom hooks 가 tanstack query 의 기본 useMutation options 를 사용 할 수 있도록 변경
* useCreatePost 에 있던 onSuccess …
=> refac&fix: #212, #214 버그 fix 와 useMutation custom hooks 리팩터링

packages/climbingweb/pages/_app.tsx, packages/climbingweb/src/hooks/useIsomorphicLayoutEffect.ts
useLayoutEffect warning 제거
- usehooks-ts 사이트에서 권고하는 ssr에서 useLayoutEffect 사용 시 warning 제거 방법 사용
- https://usehooks-ts.com/react-hook/use-isomorphic-layout-effect
=> fix: nextjs 에서 useLayoutEffect warning 제거

packages/climbingapp/src/component/webview/CustomWebView.tsx, packages/climbingweb/src/components/CenterInfo/CenterInfoHead.tsx
Fixes #213
- 기존에는 웹뷰에서 화면 전환
- 변경 후 센터 링크 선택 시 RN Linking 을 통해 전화번호, 시스템 브라우저로 링크 이동되도록 변경
- RN에 메시지를 보내서 동작하도록 변경
=> fix: 센터의 웹, 인스타, 유투브 등 링킹 방식 수정

packages/climbingweb/src/components/HomeFeed/FeedContent/FeedContent.tsx
Fixes #226 
댓글 더보기 같은 라인의 빈 공간을 클릭 했을 경우에도 댓글 창으로 가는 버그 수정
- 댓글 더보기를 div로 감싸 display flex 속성 추가
=> fix: 댓글 더보기 클릭시 버그

packages/climbingweb/pages/feed/[fid]/comments/[cid]/index.tsx, packages/climbingweb/pages/feed/[fid]/comments/index.tsx, packages/climbingweb/src/components/Comments/CommentInput.tsx
#227 댓글 인풋창 버그
댓글 인풋창의 줄 수가 2줄 이상일 때, 댓글을 작성이 완료 되어도 기본 1줄로 돌아오지 않던 현상 수정
- 댓글 인풋창의 줄 수가 2줄 이상일 때, 댓글을 작성이 완료 되어도 기본 1줄로 돌아오지 않던 현상 수정
- 댓글 페이지, 대댓글 페이지 BNB 제거
=> fix: #227 댓글 인풋창 버그 해결

packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx, packages/climbingweb/src/components/common/BottomSheetContents/ButtonSheet/index.tsx, packages/climbingweb/src/components/common/button/Button.tsx, packages/climbingweb/src/hooks/queries/post/queries.ts, packages/climbingweb/src/hooks/queries/post/queryKey.ts, packages/climbingweb/types/response/post/index.d.ts
Fixes #232
- 게시글 상세 메뉴 클릭시 본인이 작성한 피드일 경우 수정 및 삭제 메뉴 표시
- 게시글 삭제 메뉴 추가
=> feature: #게시글_상세_메뉴 #게시글_상세_메뉴_삭제

packages/climbingweb/firebase.json
firebase 웹 서버 캐시 설정 추가
-  html 
-  브라우저 캐시 유지 시간 0, 항상 revalidate
-  CDN에서 캐시 1년 유지,  
- css, js
- 브라우저 캐시 1년
- 새 빌드 시 파일 변경 => 캐시 무효화
- 그 외 리소스
- 브라우저 캐시 1년
- 프로젝트 내 리소스는 변경 가능성 없음
=> chore: firebase 캐시설정 추가

.github/workflows/chromatic.yml
크로매틱 ci 빌드 에러 해결
-  firebase 캐시 설정 추가 커밋 이후 ci 빌드 에러 발생
-  원인은 node 버전 관련 에러 (위와 상관관계는 파악x)
-  ci에 노드버전 16 lts로 설정 후 해결
=> fix:크로매틱 ci node 버전에 의한 에러 수정

packages/climbingweb/pages/feed/create/index.tsx, packages/climbingweb/src/components/CreateFeed/CenterSearchInput.tsx, packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx
Fixes #254 
게시글 생성 refactor/style
- 게시글 생성 제목을 새 게시글로 변경
- 암장 홀드 선택 모달 화면에서 홀드 아이콘 가운데 정렬
- 암장 이름 검색 텍스트 바 height 줄이기
- 암장 이름 선택 시 선택 되었음을 표시
=> style/refactor: 게시글 생성(#254)

packages/climbingweb/pages/report/[fid].tsx
Fixes #257 
fix: 게시글 신고완료 시 홈_신고_완료 화면으로 redirect
- onSuccess시 router.push 추가 
- onError 시 Error message로 toast 변경
=> fix: 게시글 신고완료 시 홈_신고_완료 화면으로 redirect

packages/climbingweb/pages/center/index.tsx, packages/climbingweb/src/components/common/CenterResult/CenterResult.tsx, packages/climbingweb/src/components/common/CenterResult/CenterResultList.tsx, packages/climbingweb/src/components/common/EmptyContent/EmptyContent.tsx
Fixes #248 
암장 메인 페이지 css 적용
- App bar 높이 변경
- 내부 element간 gap 변경
- 텍스트 사이즈 변경
- 엘리먼트 마진, 패딩 사이즈 변경
- empty content 높이 변경(empty 일 경우 figma 스타일이 존재하지 않아 content가 존재할 경우와 같은 높이로 설정하였음)
=> style: [CSS]#암장

packages/climbingapp/src/component/webview/CustomWebView.tsx, packages/climbingapp/src/hooks/useAuth.ts, packages/climbingweb/pages/_app.tsx, packages/climbingweb/pages/setting/index.tsx, packages/climbingweb/src/hooks/useAppToken.ts, packages/climbingweb/src/hooks/useToken.ts
Fixes 
#288 
#296
#297
- 로그아웃 오류 fix
- 홈 화면 최초 접속 시 토큰 오류 fix
- 회원탈퇴 기능 추가 feat 
- 로그아웃
-  로그아웃 해도 디바이스에  기존 토큰을 지우지 않고 남겨놔서 발생한 버그
-  기존 토큰을 지우고 정상 로그인 플로우를 통해 새 토큰을 발급받도록 함 
- 홈 화면
- 웹 접속용 토큰 관련 로직을 주석처리
- 앱에서 토큰 받아오는 로직  hook으로 분리
- 화면 분기처리
-  ** 기존에 화면 분기처리가 되지 않은 이유는 토큰이 정상적으로 axios header에 저장되기 전에 home 화면에 진입했기 때문에  api error call 화면을 띄움**
- 회원탈퇴
-  앱에 leave 메시지 전달
-  기존에 얍애소 작성한 회원탈퇴 로직을 통해 기능 수행
=> fix: 로그아웃 로직 수정, 탈퇴하기 기능 추가

packages/climbingapp/src/navigation/LoginNavigator.tsx, packages/climbingapp/src/navigation/screens/auth/WelcomeScreen.tsx, packages/climbingapp/src/store/slices/authInfo.ts
- 회원 가입 완료 화면에서 뒤로가기가 존재 => 제거
- 가입 완료 시 리덕스에 저장되어있던 회원가입용 입력정보 모두 초기화
=> fix: 가입완료 화면 헤더(뒤로가기) 제거, 입력정보 초기화

packages/climbingapp/src/component/webview/CustomWebView.tsx, packages/climbingapp/src/hooks/useAuth.ts, packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx
Fixes #287 
- 로그인 화면에서 구글 로그인 기록 삭제 => 다른 구글 아이디로 로그인 가능하도록 fix
- googleSignOut 함수 사용
- revokeAccess => signOut 으로 변경
- revokeAccess는 유저가 어플에 접근하는 권한도 없앰 => signout만 해도 로그인 변경에 충분함
- 이 외 revokeAccess 사용 시 발생되는 부가적인 이슈는 파악 안되었음 
- 로그인 화면 마운트 시 동작
=> feat: google 로그인 기록 삭제 적용

packages/climbingweb/pages/center/[cid]/index.tsx, packages/climbingweb/pages/center/request/[cid].tsx, packages/climbingweb/pages/feed/[fid].tsx, packages/climbingweb/pages/feed/[fid]/comments/[cid]/index.tsx, packages/climbingweb/pages/feed/[fid]/comments/index.tsx, packages/climbingweb/pages/index.tsx, packages/climbingweb/pages/report/[fid].tsx, packages/climbingweb/pages/setting/index.tsx, packages/climbingweb/pages/users/name/[uname]/index.tsx, packages/climbingweb/src/components/SettingInfo/BanList.tsx
Fixes 
#238
#291 
- 바텀시트 오픈 되었을 때 backdrop 뒤 화면의 클릭 발생하지 않도록 fix
- 바텀시트 style props에 직접 pointer-event 속성을 설정 =>  auto
- 꼭 auto 옵션이 아니어도 클릭 이슈 해결 되었음
=> fix: bottomsheet에 pointer-event props로 직접 변경해주어 backdrop 뒤 화면 클릭 방지
