Co-Laon/claon-app

.github/workflows/ci.yml, CONTRIBUTING.md, README.md
- \#3
컨트리뷰션 가이드 작성
- github 기여 방식 설명
- 개발 시 주의사항 (진행 중)
=> Contributing

.storybook/main.js, .storybook/preview.js, package.json, packages/climbingapp/src/component/Button.stories.tsx, packages/climbingapp/src/component/Button.tsx, packages/climbingweb/package.json, packages/climbingweb/pages/ExampleList.stories.tsx, packages/climbingweb/pages/ExampleList.tsx, postcss.config.js, tailwind.config.js, yarn.lock
- \#9
스토리북 적용
- react type   storybook를 프로젝트 root 위치에  설치    
- storybook addon 추가
- addon-postcss  (tailwind 적용 위해)
- addon-react-native-web  (RN 컴포넌트를 스토리북 웹에서 같이 보기 위해) 
- postcss, tailwind config 파일들 root에도 추가해줌  (storybook이 사용해야하기 때문에)
- .storybook 폴더 추가 (storybook 설정 파일들)
- storybook 동작 확인을 위한 demo component들 추가
=> chore: storybook init

.github/workflows/chromatic.yml, package.json, yarn.lock
- \#14
- pull request 시 ci 동작 test 를 위한 pull request
- pull request 시 fork repo의 secrets를 읽을 수 없으므로 fork repo에서만 사용
- chromatic yarn add 및 배포 테스트
- chromatic ci 파일 추가
=> chore: add chromatic ci for storybook

package.json, yarn.lock
- \#25
- styled components 라이브러리 전역 추가
- storybook에서도 사용해야하기 때문
- 
- package.json 변경
- yarn.lock 변경
=> chore: add styled-components for RN styles

package.json, packages/climbingweb/pages/_app.tsx, packages/climbingweb/tailwind.config.js, yarn.lock
- \#16
- web (nextjs) 다크모드 테마 설정 세팅
- next-themes 라이브러리 사용 
- tailwindConfig 다크모드 설정
=> chore: setting for darkmode-web

packages/climbingapp/App.tsx, packages/climbingapp/src/theme/index.ts
- \#15
- RN(앱) 다크모드 설정
- theme 파일 생성
- App.tsx 파일에 ThemeProvider 적용
=> chore: setting for RN darkmode

packages/climbingapp/ios/Podfile.lock, packages/climbingapp/package.json, packages/climbingapp/src/component/CustomWebView.tsx, packages/climbingapp/src/navigation/screens/main/HomeScreen.tsx, yarn.lock
- \#33
- 웹뷰 라이브러리 추가 및 웹뷰 데모 컴포넌트 구현
- react-native-webview  라이브러리 추가
- CustomWebView 컴포넌트 구현
=> feat: add react-native-webview and implement demo webview

packages/climbingweb/pages/_app.tsx, packages/climbingweb/src/store/index.ts, packages/climbingweb/src/store/slices/index.ts
- \#38
- redux store에 필요한 boilerplate 코드 추가
-  src/store/index.ts   스토어 생성 파일
-  src/store/slices/index.ts  rootReducer 생성 파일
- _app.tsx 파일에 provider 추가
=> chore: redux boilerplate setting for web

.gitignore, CONTRIBUTING.md
- None
refactor CONTRIBUTING.md
=> docs: refactor CONTRIBUTING.md

packages/climbingapp/android/app/src/main/AndroidManifest.xml, packages/climbingapp/android/app/src/main/res/values/strings.xml, packages/climbingapp/android/build.gradle, packages/climbingapp/ios/Podfile.lock, packages/climbingapp/ios/climbingApp-Bridging-Header.h, packages/climbingapp/ios/climbingApp.xcodeproj/project.pbxproj, packages/climbingapp/ios/climbingApp/AppDelegate.m, packages/climbingapp/ios/climbingApp/Info.plist, packages/climbingapp/package.json, packages/climbingapp/src/component/checkbox/Checkbox.stories.tsx, packages/climbingapp/src/component/dropdown/DropDown.stories.tsx, packages/climbingapp/src/hooks/useAuth.ts, packages/climbingapp/src/navigation/index.tsx, packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx, packages/climbingapp/src/navigation/screens/auth/WelcomeScreen.tsx, packages/climbingapp/src/store/slices/auth.ts, tailwind.config.js, yarn.lock
- \#17
- ios, aos 카카오 로그인 구현,
- react-native-kakao-login  라이브러리 사용
- IOS pod install 이슈 있음 :  arch x86_64 pod install   (m1에서는 해당 명령어로 빌드해주어야 문제 없음)
- AOS 이슈 : kotlin 버전 때문에 라이브러리 빌드가 안되는 경우 생김
- AOS 이슈2 : kakao-login 에서 권장하는 kotlin 버전 사용하면 react-native-gesture-handler가 빌드 안됨...  => kotlin 1.7.0 버전 (최신) 으로 설정해서 해결
----
- 스토리북 lint 에러 생기는 부분 수정 (중요도 👎 )
=> feat: implement KakaoLogin

packages/climbingapp/ios/Podfile.lock, packages/climbingapp/ios/climbingApp/AppDelegate.m, packages/climbingapp/ios/climbingApp/Info.plist, packages/climbingapp/package.json, packages/climbingapp/src/hooks/useAuth.ts, packages/climbingapp/src/navigation/screens/auth/LoginScreen.tsx, packages/climbingapp/src/navigation/screens/auth/WelcomeScreen.tsx, packages/climbingapp/src/store/slices/auth.ts, yarn.lock
- \#18
- react-native-google-login 라이브러리 적용,
- ios, aos 적용 완료
- useAuth Hook에서 소셜로그인, 로그아웃 모두 관리
- 이외 변경사항은 모두 설정 파일
- User attribute
- app-key 등 보안 관련 설정 추가
=> feat: implement Google Login

packages/climbingapp/.gitignore, packages/climbingapp/android/app/build.gradle, packages/climbingapp/android/app/src/main/AndroidManifest.xml, packages/climbingapp/ios/Config.xcconfig, packages/climbingapp/ios/Podfile.lock, packages/climbingapp/ios/climbingApp.xcodeproj/project.pbxproj, packages/climbingapp/ios/climbingApp.xcodeproj/xcshareddata/xcschemes/climbingApp.xcscheme, packages/climbingapp/ios/climbingApp/Info.plist, packages/climbingapp/package.json, packages/climbingapp/src/hooks/useAuth.ts, yarn.lock
- \#67
- kakao, google api-key 노출 숨김 처리
- react-native-config 라이브러리 사용
- build, runtime 시 사용되는 api-key 모두 .env에서 사용
=> chore: fix config for hide app key

.github/PULL_REQUEST_TEMPLATE.md
- \#(issue number)
refactor pull request template
- 
-
=> refactor: refactor pull request template

packages/climbingweb/styles/globals.css
Fixes #60
- global.css에 SpoqaHanSansNeo font 적용
=> chore: apply SpoqaHanSansNeo font

packages/climbingweb/src/components/common/LaonList/LaonCaencelButton.tsx, packages/climbingweb/src/components/common/LaonList/LaonItem.tsx, packages/climbingweb/src/components/common/LaonList/index.tsx, packages/climbingweb/src/components/common/LaonList/type.d.ts, packages/climbingweb/tsconfig.json
Fixes #86  
LaonList 컴포넌트 구현
-  LaonList     
- props: (닉네임, 이미지, rightNode),    rightnode에 필요한 컴포넌트 추가
-  LaonItem 
-  LaonCancelButton
=> feat: implement view of LaonList

package.json, packages/climbingweb/src/components/common/BottomSheetContents/LeaveSheet.tsx, yarn.lock
Fixes #87 
- react-spring-bottom-sheet 추가
- webview에서 모바일 bottom-sheet 대신 사용
- 설정페이지 로그아웃 바텀시트 내부시트 구현
=> feat: add web-bottomSheet library and implement LeaveSheet

packages/climbingweb/pages/index.tsx, packages/climbingweb/src/components/HomeFeed/FeedContent/FeedContent.tsx, packages/climbingweb/src/components/HomeFeed/FeedHeader/FeedHeader.tsx, packages/climbingweb/src/components/HomeFeed/FeedSectorInfo/FeedSectorInfo.tsx, packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx
피드 컴포넌트 스타일링 변경,
홈 화면 높이 조정
- feed  css style 변경 (넓이, 간격 etc..)
- home 화면에 더미 추가
=> style: change Feed styling

packages/climbingapp/src/navigation/index.tsx, packages/climbingapp/src/navigation/screens/main/CenterScreen.tsx, packages/climbingapp/src/navigation/screens/main/MyScreen.tsx, packages/climbingapp/src/navigation/screens/main/SearchScreen.tsx, packages/climbingweb/pages/CommentPage.tsx, packages/climbingweb/pages/_app.tsx, packages/climbingweb/src/components/Comments/CommentInput.tsx, packages/climbingweb/src/components/common/bottomNav/NavBar.tsx, packages/climbingweb/src/components/common/bottomNav/NavButton.tsx, packages/climbingweb/src/components/common/bottomNav/button.tsx, packages/climbingweb/src/components/common/bottomNav/type.d.ts, packages/climbingweb/styles/globals.css, packages/climbingweb/tailwind.config.js
Fixes #97
- [앱] 바텀 네비게이션 해제
- [웹] 바텀 네비게이션 구현 및 적용
- BottomNav 폴더 >  NavBar, NavButton 구현
---
- 코멘트 화면 바텀인풋 리팩토링
=> Bottom navi for web

packages/climbingweb/src/components/ImageSlider/ImageSlider.tsx, packages/climbingweb/styles/globals.css
- 폰트 에러 이슈 픽스
- 슬라이더 컴포넌트 key warning 픽스
=> fix: fix not applying font issue and imageSlider key warning issue

packages/climbingweb/pages/SettingPage.tsx, packages/climbingweb/src/components/SettingInfo/EditMyInfo.tsx, packages/climbingweb/src/components/SettingInfo/SettingList.tsx, packages/climbingweb/src/components/common/BottomSheetContents/areaSheet/AreaSheet.tsx, packages/climbingweb/src/components/common/BottomSheetContents/areaSheet/AreaSheetHeader.tsx, packages/climbingweb/src/components/common/DropDown/index.tsx, packages/climbingweb/src/components/common/button/Button.tsx, packages/climbingweb/src/components/common/divder/Divder.tsx, packages/climbingweb/src/components/common/profileImage/ProfileImage.tsx
Fixes #103 
- 세팅 페이지 내 개인정보 수정 화면 구현
- 내부 화면 구현
- 컴포넌트 구현
-  프로필이미지 
-  스몰노드버튼
=> feat: implement SettingPage >> EditMyInfo view

packages/climbingweb/pages/feed/[fid].tsx
=> feat: create page for one Feed

packages/climbingweb/pages/SettingPage.tsx, packages/climbingweb/src/components/SettingInfo/Notification/Notification.tsx, packages/climbingweb/src/components/SettingInfo/Notification/NotificationList.tsx, packages/climbingweb/src/components/SettingInfo/Notification/type.d.ts
Fixes #106 
- 공지사항 페이지 구현
- 공지사항 리스트 화면
- 공지사항 상세 화면
=> feat: implement Notification component

packages/climbingweb/pages/setting/index.tsx, packages/climbingweb/src/components/SettingInfo/BanList.tsx, packages/climbingweb/src/components/common/LaonList/LaonCaencelButton.tsx
Fixes #118 
- 설정 > 차단 리스트 화면 구현
- 설정 페이지 하위 컴포넌트인 BanList.tsx 화면 구현
-  기존에 구현된 LaonList 컴포넌트 사용
=> feat: 차단리스트 화면 구현

packages/climbingweb/pages/_document.tsx
- prefer-color-schemes   속성으로 os 다크모드 시 다크모드 자동 변경 이슈를 수정
-  _document.tsx 파일 생성하여 최상단 html 태그에 light 모드 강제 고정
=> fix: :bug: 자동 다크모드 버그 이슈 핫픽스

tailwind.config.js
storybook 에서 tailwind 플러그인 미적용 문제 해결을 위한 tailwind 플러그인 global 적용
=> fix: tailwind 플러그인 global 적용

packages/climbingweb/next.config.js, packages/climbingweb/pages/feed/create/index.tsx, packages/climbingweb/src/assets/icon/createFeed/ic_24_minus_gray800.svg, packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldImage.tsx, packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldImageButton.tsx, packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx, packages/climbingweb/src/components/CreateFeed/type.d.ts, packages/climbingweb/src/components/common/PageSubTitle/PageSubTitle.tsx, packages/climbingweb/src/interface/Hold.tsx
#124  피드 작성 페이지 마크업 구현
피드 작성 페이지 마크업 구현
- 홀드 모달 관련 minus icon 추가
- 홀드 모달 관련 컴포넌트 추가
- next.js images 관련 s3 도메인 추가
=> feat: 피드 작성 페이지 마크업 구현

packages/climbingweb/pages/_app.tsx
-  .env 환경변수 파일 추가
-  웹 환경에서 작업 시 마스터 토큰 사용 적용
=> chore: .env 환경변수 추가 및 웹 환경  작업 시 마스터 토큰 적용

packages/climbingweb/types/common/index.ts, packages/climbingweb/types/request/center/index.d.ts, packages/climbingweb/types/request/notice/index.d.ts, packages/climbingweb/types/request/post/index.d.ts, packages/climbingweb/types/request/user/index.d.ts, packages/climbingweb/types/response/center/index.ts, packages/climbingweb/types/response/laon/index.ts, packages/climbingweb/types/response/notice/index.d.ts, packages/climbingweb/types/response/post/index.d.ts, packages/climbingweb/types/response/user/index.d.ts
전체 api http response 와 request 타입 정의
=> chore: response 타입 정의

packages/climbingweb/pages/feed/[fid].tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterCharge.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterDetailInfo.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterHoldList.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterOperatingTime.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterPost.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterReview.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterSectorList.tsx, packages/climbingweb/src/components/CenterInfo/CenterInfoContent.tsx, packages/climbingweb/src/components/CreateFeed/CenterSearchInput.tsx, packages/climbingweb/src/components/CreateFeed/SelectHoldList/HoldListModal.tsx, packages/climbingweb/src/components/HomeFeed/FeedContent/FeedContent.tsx, packages/climbingweb/src/components/HomeFeed/FeedHeader/FeedHeader.tsx, packages/climbingweb/src/components/HomeFeed/FeedSectorInfo/FeedSectorInfo.tsx, packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx, packages/climbingweb/src/components/ImageSlider/ImageSlider.tsx, packages/climbingweb/src/components/SearchResult/UserResult/UserResult.tsx, packages/climbingweb/src/hooks/queries/center/useGetCenterPosts.ts, packages/climbingweb/src/hooks/queries/post/useCreateLike.ts, packages/climbingweb/src/hooks/queries/post/useDeleteLike.ts, packages/climbingweb/src/hooks/queries/post/useFindAllChildrenComment.ts, packages/climbingweb/src/hooks/queries/post/useFindAllParentCommentAndThreeChildComment.ts, packages/climbingweb/src/hooks/queries/post/useGetPost.ts
chore: hooks 디렉터리 변경에 따른 import 주소 변경
feat: fid 페이지 백엔드 로직 추가
__chore: hooks 디렉터리 변경에 따른 import 주소 변경__
- 이전 커밋에 누락된 파일 추가
---------
__feat: fid 페이지 백엔드 로직 추가__
- fid 페이지 리팩터링
- HomeFeed 관련 컴포넌트 리팩터링
=> feat&chore: fid 페이지 백엔드 로직 추가, hooks 디렉터리 변경에 따른 import 주소 변경

packages/climbingweb/src/components/CreateFeed/CenterSearchInput.tsx
bugfix: input의 select 부분 오류 수정
- input select 부분이 의도치 않게 open 되는 버그 수정
=> bugfix: input의 select 부분 오류 수정

packages/climbingapp/src/component/webview/CustomWebView.tsx
앱 로그아웃 동작 추가,
웹에서 RN으로  type: 'logout' 데이터 송신하면 로그아웃 기능 동작하도록 구현
=> feat: 앱 로그아웃 동작 추가

packages/climbingapp/package.json, yarn.lock
Please include a summary of the change and which issue is fixed.
0.67.4 -> 0.67.5 버전 업
관련 링크 https://github.com/facebook/react-native/issues/35210
- 
-
=> chore: RN 안드로이드 빌드 이슈로 0.67.4 -> 0.67.5 로 버전 업그레이드

packages/climbingweb/src/components/common/Error/ErrorContent.tsx, packages/climbingweb/src/hooks/queries/center/useFindCenter.ts, packages/climbingweb/src/hooks/queries/center/useFindHoldInfoByCenter.ts, packages/climbingweb/src/hooks/queries/center/useFindReviewByCenter.ts, packages/climbingweb/src/hooks/queries/center/useGetCenterList.ts, packages/climbingweb/src/hooks/queries/center/useGetCenterPosts.ts, packages/climbingweb/src/hooks/queries/center/useSearchCenter.ts, packages/climbingweb/src/hooks/queries/center/useSearchCenterName.ts, packages/climbingweb/src/hooks/queries/laon/useCreateLaon.ts, packages/climbingweb/src/hooks/queries/laon/useDeleteLaon.ts, packages/climbingweb/src/hooks/queries/laon/useGetLaonPost.ts, packages/climbingweb/src/hooks/queries/post/useCreateLike.ts, packages/climbingweb/src/hooks/queries/post/useCreatePost.ts, packages/climbingweb/src/hooks/queries/post/useCreateReport.ts, packages/climbingweb/src/hooks/queries/post/useDeleteLike.ts, packages/climbingweb/src/hooks/queries/post/useFindAllChildrenComment.ts, packages/climbingweb/src/hooks/queries/post/useFindAllParentCommentAndThreeChildComment.ts, packages/climbingweb/src/hooks/queries/post/useGetPost.ts, packages/climbingweb/src/hooks/queries/post/useGetPosts.ts, packages/climbingweb/src/hooks/queries/user/useSearchUser.ts, packages/climbingweb/types/common/index.d.ts
공통 에러 컴포넌트 서버 비즈니스 에러까지 커버 하도록 변경
- 공통 에러 컴포넌트에서 서버의 비즈니스 에러까지 handling 할 수 있도록 로직 추가
- develop 모든 react-query 훅에 에러 타입 추가
=> feat: 공통 요소 업데이트 및 훅 적용

CONTRIBUTING.md
컨트리뷰팅 가이드 커밋 컨벤션  style, test 추가
- style: ui 반영사항 코드 변경 시
- test: 테스트 코드 반영 시 
- [x ] End of work
=> docs: 커밋 컨벤션 추가

packages/climbingweb/src/components/Comments/Comments.tsx, packages/climbingweb/src/components/common/profileImage/ProfileImage.tsx, packages/climbingweb/styles/globals.css
fix: font 관련 css 개선, 코멘트 페이지 css 수정 및 기본 프로필 적용
- fix: font 관련 css 개선
local 폰트가 있다면 사용 하도록 추가, format 적용을 통해 불필요한 다운로드 줄임
- 코멘트 페이지 css 수정 및 기본 프로필 적용
ProfileImage 컴포넌트 기본 사이즈 추가 및 코멘트 페이지 추가 적용
=> fix: 자체 QA css 관련

packages/climbingweb/src/components/Comments/Comments.tsx, packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx, packages/climbingweb/src/components/SearchResult/UserResult/UserResult.tsx, packages/climbingweb/src/components/User/UserFeed.tsx, packages/climbingweb/src/components/User/UserRecord.tsx, packages/climbingweb/src/components/common/CenterResult/CenterResult.tsx, packages/climbingweb/src/components/common/ImageList/index.tsx, packages/climbingweb/src/components/common/skeleton/CenterImageSkeleton.tsx, packages/climbingweb/src/components/common/skeleton/CenterResultSkeleton.tsx, packages/climbingweb/src/components/common/skeleton/CommentSkeleton.tsx, packages/climbingweb/src/components/common/skeleton/FeedSkeleton.tsx, packages/climbingweb/src/components/common/skeleton/Skeleton.stories.tsx, packages/climbingweb/src/components/common/skeleton/UserFeedSkeleton.tsx, packages/climbingweb/src/components/common/skeleton/UserRecordSkeleton.tsx, packages/climbingweb/src/components/common/skeleton/UserResultSkeleton.tsx
Fixes #115 
화면에 필요한 스켈레톤 구현
https://www.chromatic.com/component?appId=626bb3b01fea16004a74f018&csfId=web-skeleton--%ED%94%BC%EB%93%9C%EC%8A%A4%EC%BC%88%EB%A0%88%ED%86%A4&buildNumber=142&k=63a98ebb7c673b73ba3ac78e-1200-interactive-true&h=18&b=-5
- 피드
- 댓글
- 검색결과
-  사용자 검색 결과
-  암장 검색 결과
-  암장
-  암장 검색 결과 (동일)
- 암장 상세
-  암장 사진     
- 마이페이지, 유저
-  기록
- 유저피드
=> 스켈레톤 구현 피드, 댓글, 암장사진, 검색 시 암장, 유저리스트, 마이페이지 기록, 피드

.github/ISSUE_TEMPLATE/BUG_REPORT.md
None
rewrite issue template about bug report
=> chore: rewrite issue template about bug report

.github/workflows/firebase-hosting-merge.yml
chore: deploy target branch 변경
- 
-
=> chore: deploy target branch 변경

packages/climbingapp/android/app/build.gradle
앱 크래시로 인한 앱 코드 난독화 false
- def enableProguardInReleaseBuilds = false
=> chore: proguard - 코드 난독화 기능 - 미사용으로 변경 -> 크래시 미발생

packages/climbingapp/src/component/appBar/AppBar.tsx, packages/climbingapp/src/component/appBar/Skip.tsx, packages/climbingapp/src/component/text-input/TextInput.tsx, packages/climbingapp/src/navigation/screens/auth/ConnectWithInstagramScreen.tsx, packages/climbingapp/src/navigation/screens/auth/SignUpStepOneScreen.tsx, packages/climbingapp/src/navigation/screens/auth/SignUpStepTwoScreen.tsx, packages/climbingapp/src/navigation/screens/auth/WelcomeScreen.tsx
Fixes #192
암리치, 인스타그램연동 화면 버그 fix
- 건너뛰기 추가 
-  AppBar 컴포넌트 왼쪽, 중앙, 오른쪽에 하위 컴포넌트 추가 가능하도록 수정
- 완료 버튼 disabled 적용
- 인풋컴포넌트 입력 시 숫자 키패드만 노출되도록 변경
- ape index 항상 노출되게 변경, cm 단위, 소수점 단위 변경
-  에러처리 적용
-  라우팅 버튼 클릭 시  홈으로 이동하게끔 수정
=> [WIP] fix: #192 사용자 정보 입력화면, 인스타그램 연동화면 버그 fix

packages/climbingapp/src/component/webview/CustomWebView.tsx, packages/climbingapp/src/hooks/useAuth.ts
- 앱에 로그아웃, 회원탈퇴 기능 수정 및 추가
- 로그아웃, 회원탈퇴 api 앱에서 처리
- toast 출력
- 웹에서 logout, leave 메시지 수신 시 동작
=> fix: 로그아웃, 회원탈퇴 로직 추가 및 수정

packages/climbingweb/pages/_app.tsx, packages/climbingweb/pages/report/[fid].tsx, packages/climbingweb/src/components/common/AppBar/IconButton.tsx, packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/ListSheet.tsx, packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/SheetHeader.tsx, packages/climbingweb/src/components/common/DropDown/index.tsx, packages/climbingweb/src/components/common/bottomNav/NavBarWrapper.tsx, packages/climbingweb/src/components/common/button/Button.tsx, packages/climbingweb/src/hooks/useBnB.ts, packages/climbingweb/src/store/slices/index.ts, packages/climbingweb/src/store/slices/manageBnb.ts
Fixes #200 
Please include a summary of the change and which issue is fixed.
- 게시물 신고 시 Bottom Navigation Bar 사라지도록 설정
- App Bar의 높이 변경
- 텍스트 사이즈 및 각 엘리먼트들의 높이와 너비 변경
- Back Button 클릭 시 router 설정
- 게시글 신고 BttomSheet의 왼쪽 정렬
- 신고 완료의 경우 버그 수정 필요
=> Style: [CSS] 게시글 신고

packages/climbingweb/pages/feed/[fid]/comments/[cid]/index.tsx, packages/climbingweb/pages/feed/[fid]/comments/index.tsx, packages/climbingweb/src/components/Comments/CommentInput.tsx, packages/climbingweb/src/components/Comments/Comments.tsx, packages/climbingweb/src/hooks/queries/post/queryKey.ts
Fixes #201 
Please include a summary of the change and which issue is fixed.
- 
-
=> refac: [CSS] 댓글

packages/climbingweb/pages/feed/[fid].tsx, packages/climbingweb/pages/index.tsx, packages/climbingweb/pages/report/[fid].tsx, packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx
Fixes #237 
Home feed 에서 bottom sheet 분리
- Home Feed 에서 Bottom Sheet 분리
- home/index.tsx에 Bottom Sheet 추가
- feed/[fid].tsx Bottom Sheet 추가
=> refactor: bottom sheet 분리

packages/climbingweb/pages/center/[cid]/index.tsx, packages/climbingweb/pages/center/request/[cid].tsx, packages/climbingweb/src/components/common/BottomSheetContents/ListSheet/ListSheet.tsx, packages/climbingweb/src/components/common/DropDown/index.tsx, packages/climbingweb/src/components/common/Toast/Toast.tsx
Fixes #251 
Style: [CSS] 암장 수정 요청
- text size/line height/font weight 변경
- 패딩 변경
- 암장 수정 요청시 api 호출 전에 onClick 함수가 끝나버리는 버그 수정
=> Style: [CSS] 암장 수정 요청

packages/climbingweb/src/components/ImageSlider/ImageSlider.tsx, packages/climbingweb/src/components/common/StarRating/index.tsx
Fixes #253 
게시글 image 배경 색 설정(
- 게시글 image 배경 색 설정(
=> style: 게시글 image 배경 색 설정(#253)

packages/climbingweb/src/components/HomeFeed/FeedHeader/FeedHeader.tsx, packages/climbingweb/src/components/HomeFeed/HomeFeed.tsx, packages/climbingweb/src/components/common/StarRating/index.tsx
Fixes #242 
프로필 마이페이지 버그 fix
- FeedHeader에 isOnwer 를 props로 전달하여 true이면 본인 마이페이지로 이동 
- 아니면 다른 사람 마이페이지로 이동하도록 설정
=> fix: 프로필 마이페이지 bug fix(#242)

packages/climbingweb/pages/feed/create/index.tsx, packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterReview.tsx, packages/climbingweb/src/components/Comments/ReviewComment.tsx, packages/climbingweb/src/components/common/StarRating/index.tsx
Fixes #255 
fix: 게시글 생성 버그
- 500자 이상 입력시 500자 이상 입력했음을 표시
- 뒤로가기 버그의 경우 이전에 처리하였음.
=> fix: 게시글 생성 버그

packages/climbingweb/pages/center/[cid]/review/[rid].tsx, packages/climbingweb/src/components/Comments/ReviewComment.tsx, packages/climbingweb/src/components/common/StarRating/index.tsx, packages/climbingweb/src/components/common/TextArea/TextArea.tsx, packages/climbingweb/src/hooks/queries/center/queryKey.ts, packages/climbingweb/src/hooks/useReview.ts, packages/climbingweb/src/store/slices/centerReview.ts, packages/climbingweb/src/store/slices/index.ts
Fixes #269
암장 수정화면
- textarea value -> defaultValue
- 수정화면 추가
=> 암장 댓글 수정화면(#269)

packages/climbingweb/pages/users/me/laon/index.tsx
Fixes #279
[CSS] 라온 리스트
- 패딩 수정
- 취소 메시지 변경
=> [CSS] 라온 리스트 (#279)

packages/climbingweb/pages/setting/index.tsx, packages/climbingweb/src/components/SettingInfo/BanList.tsx, packages/climbingweb/src/components/SettingInfo/Notification/Notification.tsx, packages/climbingweb/src/components/SettingInfo/Notification/NotificationList.tsx, packages/climbingweb/src/components/SettingInfo/VersionInfo.tsx, packages/climbingweb/src/components/common/AppBar/index.tsx, packages/climbingweb/src/components/common/BottomSheetContents/ButtonSheet/index.tsx, packages/climbingweb/src/components/common/button/Button.tsx, packages/climbingweb/src/components/common/divder/Divder.tsx, packages/climbingweb/src/hooks/queries/notice/queries.ts, packages/climbingweb/src/hooks/queries/user/queryKey.ts
Fixes #278 
[CSS] 앱 설정
- 앱 설정 진입 시 Bottom Navigation Bar hide
- text-size/font-weight/line-height 설정
- Ban list 취소 -> 해제
=> Style: [CSS] 앱 설정(#278)

packages/climbingweb/package.json, packages/climbingweb/pages/_app.tsx, packages/climbingweb/pages/center/[cid]/index.tsx, packages/climbingweb/pages/feed/[fid].tsx, packages/climbingweb/pages/feed/[fid]/comments/[cid]/index.tsx, packages/climbingweb/pages/feed/[fid]/comments/index.tsx, packages/climbingweb/pages/feed/create/index.tsx, packages/climbingweb/pages/setting/index.tsx, packages/climbingweb/pages/users/me/laon/index.tsx, packages/climbingweb/pages/users/name/[uname]/index.tsx, packages/climbingweb/src/components/Transition/SlideRight.tsx, yarn.lock
Fixes #122 
- 화면 전환 트랜지션 적용
- framer-motion  **라이브러리** 적용
- 최신 버전은 react18v  base 이기에  v6 적용 
- 화면 트랜진션 컴포넌트를 해당 페이지 컴포넌트에 적용
- 현재 exit 시에는 애니메이팅이 안되는 이슈 있음 ( 사용하다가 추가적으로 해결 가능할 듯 합니다)
=> feat: 화면 트랜지션 애니메이션 적용

packages/climbingweb/src/components/CenterInfo/CenterDetailInfo/CenterPostFilter.tsx
Fixes #293 
Style: 암장 게시글 전체 활성화 스타일 추가(#293)
- 전체 활성화 코드 스타일 추가
=> Style: 암장 게시글 전체 활성화 스타일 추가(#293)
